# Generated by Django 4.2.3 on 2023-10-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('salario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=240)),
                ('precio', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioServicio',
            fields=[
                ('idUsuarioServicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servicio')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='servicioempleado',
            fields=[
                ('idServicioEmpleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.empleado')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('fechaPago', models.DateField()),
                ('monto', models.CharField(max_length=50)),
                ('estadoPago', models.CharField(max_length=50)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.usuario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=50)),
                ('hora', models.TimeField()),
                ('servicio', models.CharField(max_length=50)),
                ('empleado', models.CharField(max_length=50)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.usuario')),
            ],
        ),
    ]
