# Generated by Django 4.2.3 on 2023-10-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Empleado'), (3, 'Usuario')], default=3),
        ),
    ]
